routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/','App\Http\Controllers\StudentController');
Route::resource('students','App\Http\Controllers\StudentController');
Route::resource('marks','App\Http\Controllers\MarkController');

app/Models/Mark.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mark extends Model
{
    use HasFactory;
    public function student() {
        return $this->belongsTo('App\Models\Student');
    }

    protected $fillable = [
        'student_id','maths', 'science','history','term' 
    ];
}

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;
    protected $fillable = [
        'name','age', 'gender','teacher', 
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MarkController.php
<?php

namespace App\Http\Controllers;

use App\Models\Mark;
use App\Models\Student;
use Illuminate\Http\Request;

class MarkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $arr['marks'] = Mark::all();
        return view('marks.index')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $arr['students'] = Student::all();
        return view('marks.create')->with($arr);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Mark $mark)
    {
        $mark->student_id = $request->student_id;
        $mark->maths = $request->maths;
        $mark->science = $request->science;
        $mark->history = $request->history;
        $mark->term = $request->term;
        $mark->save();
        return redirect()->route('marks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Mark  $mark
     * @return \Illuminate\Http\Response
     */
    public function show(Mark $mark)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Mark  $mark
     * @return \Illuminate\Http\Response
     */
    public function edit(Mark $mark)
    {
        $arr['mark'] = $mark;
        $arr['students'] = Student::all();
        return view('marks.edit')->with($arr);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Mark  $mark
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Mark $mark)
    {
        $mark->student_id = $request->student_id;
        $mark->maths = $request->maths;
        $mark->science = $request->science;
        $mark->history = $request->history;
        $mark->term = $request->term;
        $mark->save();
        return redirect()->route('marks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Mark  $mark
     * @return \Illuminate\Http\Response
     */
    public function destroy(Mark $mark)
    {
        $mark->delete();
        return redirect()->route('marks.index');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $arr['students'] = Student::all();
        return view('students.index')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('students.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Student $student)
    {  
        $student->name = $request->name;
        $student->age = $request->age;
        $student->gender = $request->gender;
        $student->teacher = $request->teacher;
        $student->save();
        return redirect()->route('students.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        $arr['student'] = $student;
        return view('students.edit')->with($arr);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        $student->name = $request->name;
        $student->age = $request->age;
        $student->gender = $request->gender;
        $student->teacher = $request->teacher;
        $student->save();
        return redirect()->route('students.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        $student->delete();
        return redirect()->route('students.index');
    }
}

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Mangement System</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <section style="padding-top:60px";>
        <div class="container">
            @yield('content')
        </div>
    </section>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

resources/views/marks/create.blade.php
@extends('layout')
@section('content')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Add Marks</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ url('marks' )}}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Add Marks</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <form method="post" action="{{route('marks.store') }}" enctype="multipart/form-data">
        <input type="hidden" name="_token" value="{{csrf_token() }}">
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Student Name</label>
                    <div class="col-md-6">
                    <select name="student_id" class="form-control">
                    <option value="">Choose Student</option>
                    @foreach($students as $student)
                    <option value="{{$student->id}}">{{$student->name}}</option>
                    @endforeach
                    </select>
                    <div class="clearfix"></div>
                </div>
            </div>
            <br>
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Maths</label>
                    <div class="col-md-6"><input type="text" name="maths" class="form-control"></div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Science</label>
                    <div class="col-md-6"><input type="text" name="science" class="form-control"></div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">History</label>
                    <div class="col-md-6"><input type="text" name="history" class="form-control"></div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Term</label>
                    <div class="col-md-6">
                    <select name="term" class="form-control">
                        <option value="">Choose Term</option>
                        <option value="One">One</option>
                        <option value="Two">Two</option>
                    </select>
                    <div class="clearfix"></div>
                </div>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" class="btn btn-info" value="Save">
            </div>
        </form>
    </div>
</section>

@endsection

resources/views/marks/edit.blade.php
@extends('layout')
@section('content')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Edit Marks</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ url('marks' )}}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Edit Marks</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <form method="post" action="{{route('marks.update', $mark->id) }}" enctype="multipart/form-data">
        {{ method_field('PUT') }}{{csrf_field()}}
        <input type="hidden" name="_token" value="{{csrf_token() }}">
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Student Name</label>
                    <div class="col-md-6">
                    <select name="student_id" class="form-control">
                    <option value="">Choose Student</option>
                    @foreach($students as $student)
                    <option value="{{$student->id}}"

                    @if($student->id == $mark->student_id)
                    selected
                    @endif

                    >{{$student->name}}</option>
                    @endforeach
                    </select>
                    <div class="clearfix"></div>
                </div>
            </div>
            <br>
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Maths</label>
                    <div class="col-md-6"><input type="text" name="maths" class="form-control" value="{{$mark->maths }}"></div>
                    <div class="clearfix"></div>
                </div>
            </div> 
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Science</label>
                    <div class="col-md-6"><input type="text" name="science" class="form-control" value="{{$mark->science }}"></div>
                    <div class="clearfix"></div>
                </div>
            </div> 
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">History</label>
                    <div class="col-md-6"><input type="text" name="history" class="form-control" value="{{$mark->history }}"></div>
                    <div class="clearfix"></div>
                </div>
            </div> 
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Term</label>
                    <div class="col-md-6">
                    <select name="term" class="form-control">
                        <option value="">Choose Term</option>
                        <option value="One" {{ $mark->term == 'One' ? 'selected' : '' }}>One</option>
                        <option value="Two" {{ $mark->term == 'Two' ? 'selected' : '' }}>Two</option>
                    </select>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-info" value="Save">
            </div>
        </form>
    </div>
</section>

@endsection

resources/views/marks/index.blade.php
@extends('layout')
@section('content')


<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Score Board</h1>
            </div>
            <div class="col-sm-6">
                <div class="col-sm-6">
                    <ol class="nav nav-second-level">
                        <li class="breadcrumb-item {{ Request::segment(1) === 'students' ? 'active' : null }}"><a style= "text-decoration: none; color: inherit;" href="{{ url('students' )}}">Students</a></li>
                        <li class="breadcrumb-item {{ Request::segment(1) === 'marks' ? 'active' : null }}"><a style= "text-decoration: none; color: inherit;" href="{{ url('marks' )}}">Score Board</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <p>
            <a href="{{route('marks.create') }}" class="btn btn-primary">Add Marks</a>
        </p>
        <table class="table table-bordered table-stripped">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Maths</th>
                <th>Science</th>
                <th>History</th>
                <th>Term</th>
                <th>Total Marks</th>
                <th>Created On</th>
                <th>Action</th>
            </tr>
            @if(count($marks))
            @foreach($marks as $mark) 
                <tr>
                    <td>{{$mark->id}}</td>
                    <td>{{$mark->student->name}}</td>
                    <td>{{$mark->maths}}</td>
                    <td>{{$mark->science}}</td>
                    <td>{{$mark->history}}</td>
                    <td>{{$mark->term}}</td>
                    <?php $total_marks = (($mark->maths)+($mark->science)+($mark->history)); ?>
                    <td>{{$total_marks}}</td>
                    <td>{{ date_format($mark->created_at, 'M d, Y h:i A') }}</td>
                    <td>
                        <a href="{{route('marks.edit', $mark->id) }}" class="btn btn-info">Edit</a> 
                        <a href="javascript:void(0)" onclick="$(this).parent().find('form').submit()" class="btn btn-danger">Delete</a>
                        <form action="{{route('marks.destroy', $mark->id) }}" method="post">
                            @method('DELETE')
                            <input type="hidden" name="_token" value="{{csrf_token() }}">
                        </form>

                    </td>
                </tr>
            @endforeach
            @else
            <tr><td colspan="9">No marks Found</td></tr>
            @endif
        </table>
    </div>
</section>

@endsection

resources/views/students/create.blade.php
@extends('layout')
@section('content')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Add Student</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ url('students' )}}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Add Student</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <form method="post" action="{{route('students.store') }}" enctype="multipart/form-data">
        <input type="hidden" name="_token" value="{{csrf_token() }}">
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Name</label>
                    <div class="col-md-6"><input type="text" name="name" class="form-control"></div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Age</label>
                    <div class="col-md-6"><input type="text" name="age" class="form-control"></div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Gender</label>
                    <div class="col-md-6">
                        <div class="form-check form-check-inline">
                            <input type="radio" class="form-check-input" name="gender" value="M">
                            <label style="font-weight: normal !important;">Male</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input type="radio" class="form-check-input" name="gender" value="F">
                            <label style="font-weight: normal !important;">Female</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input type="radio" class="form-check-input" name="gender" value="other">
                            <label style="font-weight: normal !important;">Other</label>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Reporting Teacher</label>
                    <div class="col-md-6">
                    <select name="teacher" class="form-control">
                        <option value="">Choose Reporting Teacher</option>
                        <option value="Katie">Katie</option>
                        <option value="Max">Max</option>
                    </select>
                    <div class="clearfix"></div>
                </div>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" class="btn btn-info" value="Save">
            </div>
        </form>
    </div>
</section>

@endsection

resources/views/students/edit.blade.php
@extends('layout')
@section('content')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Edit Student</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ url('students' )}}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Edit Student</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <form method="post" action="{{route('students.update', $student->id) }}" enctype="multipart/form-data">
        {{ method_field('PUT') }}{{csrf_field()}}
        <input type="hidden" name="_token" value="{{csrf_token() }}">
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Name</label>
                    <div class="col-md-6"><input type="text" name="name" class="form-control" value="{{$student->name }}"></div>
                    <div class="clearfix"></div>
                </div>
            </div> 
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Age</label>
                    <div class="col-md-6"><input type="text" name="age" class="form-control" value="{{$student->age }}"></div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Gender</label>
                    <div class="col-md-6">
                        <div class="form-check form-check-inline">
                            <input type="radio" class="form-check-input" name="gender" value="M" {{ $student->gender == 'M' ? 'checked' : '' }}>
                            <label style="font-weight: normal !important;">Male</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input type="radio" class="form-check-input" name="gender" value="F" {{ $student->gender == 'F' ? 'checked' : '' }}>
                            <label style="font-weight: normal !important;">Female</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input type="radio" class="form-check-input" name="gender" value="other" {{ $student->gender == 'other' ? 'checked' : '' }}>
                            <label style="font-weight: normal !important;">Other</label>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <label class="col-md-3">Reporting Teacher</label>
                    <div class="col-md-6">
                    <select name="teacher" class="form-control">
                        <option value="">Choose Reporting Teacher</option>
                        <option value="Katie" {{ $student->teacher == 'Katie' ? 'selected' : '' }}>Katie</option>
                        <option value="Max" {{ $student->teacher == 'Max' ? 'selected' : '' }}>Max</option>
                    </select>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-info" value="Save">
            </div>
        </form>
    </div>
</section>

@endsection

resources/views/students/index.blade.php
@extends('layout')
@section('content')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Students Record</h1>
            </div>
            <div class="col-sm-6">
                <ol class="nav nav-second-level">
                    <li class="breadcrumb-item {{ Request::segment(1) === 'students' ? 'active' : null }}"><a style= "text-decoration: none; color: inherit;" href="{{ url('students' )}}">Students</a></li>
                    <li class="breadcrumb-item {{ Request::segment(1) === 'marks' ? 'active' : null }}"><a style= "text-decoration: none; color: inherit;" href="{{ url('marks' )}}">Score Board</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <p>
            <a href="{{route('students.create') }}" class="btn btn-primary">Add New student</a>
        </p>
        <table class="table table-bordered table-stripped">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Reporting Teacher</th>
                <th>Action</th>
            </tr>
            @if(count($students))
            @foreach($students as $student) 
                <tr>
                    <td>{{$student->id}}</td>
                    <td>{{$student->name}}</td>
                    <td>{{$student->age}}</td>
                    <td>{{$student->gender}}</td>
                    <td>{{$student->teacher}}</td>
                    <td>
                        <a href="{{route('students.edit', $student->id) }}" class="btn btn-info">Edit</a> 
                        <a href="javascript:void(0)" onclick="$(this).parent().find('form').submit()" class="btn btn-danger">Delete</a>
                        <form action="{{route('students.destroy', $student->id) }}" method="post">
                            @method('DELETE')
                            <input type="hidden" name="_token" value="{{csrf_token() }}">
                        </form>

                    </td>
                </tr>
            @endforeach
            @else
            <tr><td colspan="6">No Students Found</td></tr>
            @endif
        </table>
    </div>
</section>

@endsection